repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 22.3.0
    hooks:
      - id: black
        name: "black"
        args: ["--config=pyproject.toml"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: ["--settings=pyproject.toml", "--config-root=.", "--resolve-all-configs"]
