args:
  ansatz: orbformer-se
  autoresume: true
  balance_grad: true
  chkpt: null
  chkpts_fast_interval: 101
  chkpts_slow_interval: 10000
  chkpts_steps: null
  clip_width: 5.0
  convergence_criterion_period: 1000
  convergence_threshold: 0
  damping: 0.001
  data_augmentation:
  - rotation
  - fuzz
  data_file_whitelist: null
  data_json_whitelist: null
  data_loader: default
  dataset: lightatomcurriculum/level2
  decorr_steps: 60
  det_penalty_weight: 0.001
  discard_sampler_state: true
  ecp: false
  edge_feats: true
  electron_batch_size: 1024
  eq_auto_exit: true
  f_criterion: false
  flash_attn: true
  increment_max_charge: 0
  increment_max_down: 0
  increment_max_nuc: 0
  increment_max_species: null
  increment_max_up: 0
  jax_matmul_precision: high
  laplacian: forward
  learning_rate: 0.05
  local_energy_chunk_size: null
  max_data_set_size: null
  max_eq_steps: 300
  max_restarts: 200
  mcmc: metropolis
  mcmc_n_block: 1
  mcmc_permutations: false
  mcmc_pruning: true
  metric_logger:
  - tb
  - h5
  metric_logger_period: 25
  mol_batch_size: 16
  multi_system_sampler: double-langevin
  n_determinants: 16
  n_envelopes_per_nucleus: 8
  n_pretrain_mols: null
  no_sync_sampler_state: false
  norm_constraint: 0.001
  optimizer: kfac
  orb_parameter_mode: chem-pretrain
  pfaffian: false
  pretrain_equilibration: true
  pretrain_learning_rate: 0.001
  pretrain_mode: mo
  pretrain_steps: 0
  repeat_single_mol: false
  repeated_sampling_len: 40
  report_unclipped_energy: true
  seed: 42
  spring_mu: 0.99
  stop_early: false
  test: false
  train_steps: 400000
  workdir: null
dims:
  max_charge: 9
  max_down: 12
  max_nuc: 8
  max_species: 9
  max_up: 12
