name: precommit

permissions:
  contents: read

on: [push, pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install pre-commit
        pre-commit install
    - name: Run precommit tests
      run: |
        pre-commit run --verbose --all-files isort
        pre-commit run --verbose --all-files black
