# Uses: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda env create -f environment-os.yaml -n oneqmc
    - name: Test with pytest
      run: |
        JAX_PLATFORMS=cpu conda run -n oneqmc python -m pytest tests/
